[package]
name = "katcp"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"
chrono = "0.4"

[dependencies.katcp_derive]
path = "katcp_derive"
version = "0.1.0"

[workspace]
members = ["katcp_derive"]
