[package]
name = "katcp_derive"
version = "0.1.0"
authors = [ "Kiran Shila <me@kiranshila.com>" ]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Proc macros to accompany the katcp packages"
homepage = "https://github.com/GReX-Telescope/katcp"
respository = "https://github.com/GReX-Telescope/katcp"
readme = "../README.md"

[lib]
proc_macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.5"
